version: '2'
services:
  nginx:
    image : nginx:stable
    restart: always
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live:/mycerts 
    ports:
      - 443:443
      - 80:80
    depends_on:
      - onlyoffice
      - app 

  onlyoffice:
    image: onlyoffice/4testing-documentserver-ie
    restart: always
    volumes:
      - /app/onlynext/Data:/var/www/onlyoffice/Data
      - /app/onlynext/log:/var/log/onlyoffice

  app:
    image: nextcloud
    volumes:
      - /app/onlynext/html:/var/www/html
    depends_on:
      - onlyoffice
    restart: always

